/* This is an automatically generated file */
function loadData()
{
aTmpItems = new Array()
   aTmpItems[0] = new item("Viewing Information in the Security Window", "coll.htm#HELP_SEC_INFO", "nethelp:netscape/Collabra:HELP_SEC_INFO")
   aTmpContainers[0] = new container("Getting Security Information", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("", "coll.htm#HELP_SEC_CERTS_YOURS", "nethelp:netscape/Collabra:HELP_SEC_CERTS_YOURS")
   aTmpItems[1] = new item("Getting Securiy Certificates", "coll.htm#sec_getcerts", "nethelp:netscape/Collabra:sec_getcerts")
   aTmpItems[2] = new item("Sending Signed and Encrypted Messages", "coll.htm#HELP_SEC_INFO_OUTGOING", "nethelp:netscape/Collabra:HELP_SEC_INFO_OUTGOING")
   aTmpItems[3] = new item("", "coll.htm#HELP_SEC_CERTS_APPLETS", "nethelp:netscape/Collabra:HELP_SEC_CERTS_APPLETS")
   aTmpItems[4] = new item("", "coll.htm#HELP_SEC_CERTS_SITES", "nethelp:netscape/Collabra:HELP_SEC_CERTS_SITES")
   aTmpItems[5] = new item("", "coll.htm#HELP_SEC_CERTS_PEOPLE", "nethelp:netscape/Collabra:HELP_SEC_CERTS_PEOPLE")
   aTmpItems[6] = new item("Viewing, Editing, Verifying, and Deleting Certificates and Signers", "coll.htm#HELP_SEC_CERTS_ISSUERS", "nethelp:netscape/Collabra:HELP_SEC_CERTS_ISSUERS")
   aTmpItems[7] = new item("Choosing a Password to Protect Your Certificates", "coll.htm#HELP_SEC_PASS_UNSET", "nethelp:netscape/Collabra:HELP_SEC_PASS_UNSET")
   aTmpContainers[1] = new container("Setting up Security", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Setting Security Preferences for Browsing", "coll.htm#HELP_SEC_PREFS_NAVIGATOR", "nethelp:netscape/Collabra:HELP_SEC_PREFS_NAVIGATOR")
   aTmpItems[1] = new item("Setting Security Preferences for Sending Messages", "coll.htm#HELP_SEC_PREFS_MESSENGER", "nethelp:netscape/Collabra:HELP_SEC_PREFS_MESSENGER")
   aTmpItems[2] = new item("Controlling Access of Java Applets and JavaScripts", "coll.htm#HELP_SEC_PREFS_APPLET", "nethelp:netscape/Collabra:HELP_SEC_PREFS_APPLET")
   aTmpContainers[2] = new container("Setting Security Preferences", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Viewing and Editing Security Modules", "coll.htm#HELP_SEC_CERTS_CRYPTOMODS", "nethelp:netscape/Collabra:HELP_SEC_CERTS_CRYPTOMODS")
   aTmpContainers[3] = new container("Using Security Modules", aTmpItems)

aDatasets["coll.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Starting from a New Page", "comp.htm#create_document", "nethelp:netscape/Composer:create_document")
   aTmpItems[1] = new item("Checking the Spelling", "comp.htm#SPELL_CHECK", "nethelp:netscape/Composer:SPELL_CHECK")
   aTmpItems[2] = new item("About the Edit Dictionary Dialog Box", "comp.htm#EDIT_DICTIONARY", "nethelp:netscape/Composer:EDIT_DICTIONARY")
   aTmpItems[3] = new item("Saving and Browsing Your New Page", "comp.htm#browse_new_page", "nethelp:netscape/Composer:browse_new_page")
   aTmpContainers[0] = new container("Creating Web Pages", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Formatting a Paragraph", "comp.htm#PROPERTIES_PARAGRAPH", "nethelp:netscape/Composer:PROPERTIES_PARAGRAPH")
   aTmpItems[1] = new item("Character Formats", "comp.htm#PROPERTIES_CHARACTER", "nethelp:netscape/Composer:PROPERTIES_CHARACTER")
   aTmpItems[2] = new item("Inserting Horizontal Lines", "comp.htm#PROPERTIES_HRULE", "nethelp:netscape/Composer:PROPERTIES_HRULE")
   aTmpItems[3] = new item("Inserting Raw HTML", "comp.htm#HTML_TAG", "nethelp:netscape/Composer:HTML_TAG")
   aTmpItems[4] = new item("About the Extra HTML Tag Dialog Box", "comp.htm#EXTRA_HTML", "nethelp:netscape/Composer:EXTRA_HTML")
   aTmpContainers[1] = new container("Formatting Your Web Page", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Inserting a Table", "comp.htm#Inserting_a_table", "nethelp:netscape/Composer:Inserting_a_table")
   aTmpItems[1] = new item("Adding and Deleting Rows, Columns, and Cells", "comp.htm#addtable", "nethelp:netscape/Composer:addtable")
   aTmpItems[2] = new item("Changing a Table", "comp.htm#Setting_table_properties", "nethelp:netscape/Composer:Setting_table_properties")
   aTmpItems[3] = new item("Using the Table Properties Dialog Box", "comp.htm#TABLE_PROPERTIES", "nethelp:netscape/Composer:TABLE_PROPERTIES")
   aTmpItems[4] = new item("Moving, Copying, and Deleting Tables", "comp.htm#select_table", "nethelp:netscape/Composer:select_table")
   aTmpContainers[2] = new container("Adding tables to your Web page", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Inserting an Image", "comp.htm#Insert_an_image", "nethelp:netscape/Composer:Insert_an_image")
   aTmpItems[1] = new item("About the Images Properties Dialog Box", "comp.htm#PROPERTIES_IMAGE", "nethelp:netscape/Composer:PROPERTIES_IMAGE")
   aTmpItems[2] = new item("About the Alternate Image Properties Dialog Box", "comp.htm#PROPERTIES_IMAGE_ALT", "nethelp:netscape/Composer:PROPERTIES_IMAGE_ALT")
   aTmpItems[3] = new item("About the Image Conversion Dialog Box", "comp.htm#IMAGE_CONVERSION", "nethelp:netscape/Composer:IMAGE_CONVERSION")
   aTmpContainers[3] = new container("Adding Pictures (Images) to Your Web Page", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Setting Page Location, Title, and Author", "comp.htm#DOCUMENT_PROPERTIES_GENERAL", "nethelp:netscape/Composer:DOCUMENT_PROPERTIES_GENERAL")
   aTmpItems[1] = new item("Setting Page Colors and Backgrounds", "comp.htm#DOCUMENT_PROPERTIES_APPEARANCE", "nethelp:netscape/Composer:DOCUMENT_PROPERTIES_APPEARANCE")
   aTmpItems[2] = new item("Specifying Meta Tags", "comp.htm#DOCUMENT_PROPERTIES_ADVANCED", "nethelp:netscape/Composer:DOCUMENT_PROPERTIES_ADVANCED")
   aTmpContainers[4] = new container("Settings Page Properties", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Linking Within the Same Page", "comp.htm#PROPERTIES_TARGET", "nethelp:netscape/Composer:PROPERTIES_TARGET")
   aTmpItems[1] = new item("Linking to Other Pages", "comp.htm#creating_links", "nethelp:netscape/Composer:creating_links")
   aTmpItems[2] = new item("About the Link Properties Dialog Box", "comp.htm#PROPERTIES_LINK", "nethelp:netscape/Composer:PROPERTIES_LINK")
   aTmpItems[3] = new item("Linking to Images", "comp.htm#Linking_images", "nethelp:netscape/Composer:Linking_images")
   aTmpItems[4] = new item("Putting Your Page on the Web", "comp.htm#PUBLISH_FILES", "nethelp:netscape/Composer:PUBLISH_FILES")
   aTmpContainers[5] = new container("Linking and Publishing Your Page", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Installing Plug-Ins", "comp.htm#COMPOSER_PLUGINS", "nethelp:netscape/Composer:COMPOSER_PLUGINS")
   aTmpContainers[6] = new container("Adding New Functions to Composer", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Composer Preferences - General", "comp.htm#PREFERENCES_EDITOR_GENERAL", "nethelp:netscape/Composer:PREFERENCES_EDITOR_GENERAL")
   aTmpItems[1] = new item("Composer Preferences - Publish", "comp.htm#PREFERENCES_EDITOR_PUBLISH", "nethelp:netscape/Composer:PREFERENCES_EDITOR_PUBLISH")
   aTmpContainers[7] = new container("Setting Composer Preferences", aTmpItems)

aDatasets["comp.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Browsing the Web", "home.htm#start_here", "nethelp:netscape/Home:start_here")
   aTmpItems[1] = new item("Using Email", "home.htm#email", "nethelp:netscape/Home:email")
   aTmpItems[2] = new item("Creating Web Pages", "home.htm#Composer", "nethelp:netscape/Home:Composer")
   aTmpItems[3] = new item("Newsgroups", "home.htm#newsgroups", "nethelp:netscape/Home:newsgroups")
   aTmpItems[4] = new item("Working Offline", "home.htm#offline", "nethelp:netscape/Home:offline")
   aTmpItems[5] = new item("Security", "home.htm#Security", "nethelp:netscape/Home:Security")
   aTmpItems[6] = new item("Troubleshooting", "home.htm#trouble", "nethelp:netscape/Home:trouble")
   aTmpContainers[0] = new container("Click one:", aTmpItems)

aDatasets["home.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Opening Your Inbox", "mess.htm#OPEN_INBOX", "nethelp:netscape/Messengr:OPEN_INBOX")
   aTmpItems[1] = new item("Choosing How You View the Messenger Window", "mess.htm#VIEW_MESSENGER_WINDOW", "nethelp:netscape/Messengr:VIEW_MESSENGER_WINDOW")
   aTmpItems[2] = new item("Choosing Between IMAP and POP3 Mail Servers", "mess.htm#IMAP_and_POP3", "nethelp:netscape/Messengr:IMAP_and_POP3")
   aTmpItems[3] = new item("Using the Mail & Newsgroups Setup Program", "mess.htm#MAIL_NEWS_WIZARD", "nethelp:netscape/Messengr:MAIL_NEWS_WIZARD")
   aTmpContainers[0] = new container("Getting Started with Mail", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("New Mail Notification", "mess.htm#notifying", "nethelp:netscape/Messengr:notifying")
   aTmpItems[1] = new item("Sorting and Threading Messages", "mess.htm#thread_mail", "nethelp:netscape/Messengr:thread_mail")
   aTmpItems[2] = new item("Saving and Printing Messages", "mess.htm#mail_selecting", "nethelp:netscape/Messengr:mail_selecting")
   aTmpContainers[1] = new container("Reading Messages", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Composing Mail and Newsgroup Messages", "mess.htm#COMPOSING_MESSAGES", "nethelp:netscape/Messengr:COMPOSING_MESSAGES")
   aTmpItems[1] = new item("Using the Message Composition Window", "mess.htm#NEW_MESSAGE_WINDOW", "nethelp:netscape/Messengr:NEW_MESSAGE_WINDOW")
   aTmpItems[2] = new item("Addressing a Message", "mess.htm#ADDRESSING_MESSAGE", "nethelp:netscape/Messengr:ADDRESSING_MESSAGE")
   aTmpItems[3] = new item("Selecting Message Sending Options", "mess.htm#SENDING_OPTIONS", "nethelp:netscape/Messengr:SENDING_OPTIONS")
   aTmpItems[4] = new item("Replying to a Message", "mess.htm#mail_replyto", "nethelp:netscape/Messengr:mail_replyto")
   aTmpItems[5] = new item("Forwarding a Message", "mess.htm#FORWARD_MESSAGES", "nethelp:netscape/Messengr:FORWARD_MESSAGES")
   aTmpItems[6] = new item("Saving and Re-using a Message Draft", "mess.htm#saving_message_draft", "nethelp:netscape/Messengr:saving_message_draft")
   aTmpItems[7] = new item("Creating or Using a Message Template", "mess.htm#mail_template", "nethelp:netscape/Messengr:mail_template")
   aTmpItems[8] = new item("Using the HTML Mail Question Dialog Box", "mess.htm#HTML_MAIL_QUESTION", "nethelp:netscape/Messengr:HTML_MAIL_QUESTION")
   aTmpItems[9] = new item("Using the Recipients Panel", "mess.htm#HTML_MAIL_QUESTION_RECIPIENT", "nethelp:netscape/Messengr:HTML_MAIL_QUESTION_RECIPIENT")
   aTmpItems[10] = new item("Using Your Palm Pilot with Messenger", "mess.htm#PALMPILOT_MAIL", "nethelp:netscape/Messengr:PALMPILOT_MAIL")
   aTmpContainers[2] = new container("Sending Messages", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Attaching a File, Web Page, or Personal Card", "mess.htm#attaching_file", "nethelp:netscape/Messengr:attaching_file")
   aTmpItems[1] = new item("Viewing and Opening Attachments", "mess.htm#viewing_attachments", "nethelp:netscape/Messengr:viewing_attachments")
   aTmpItems[2] = new item("Saving Attachments", "mess.htm#saving_attachment", "nethelp:netscape/Messengr:saving_attachment")
   aTmpItems[3] = new item("Deleting Messages", "mess.htm#about_deleting_email", "nethelp:netscape/Messengr:about_deleting_email")
   aTmpItems[4] = new item("Moving Messages to and from the Trash", "mess.htm#moving_to_trash", "nethelp:netscape/Messengr:moving_to_trash")
   aTmpContainers[3] = new container("Using Attachments", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Creating an Address Book", "mess.htm#CREATE_ADD_BOOK", "nethelp:netscape/Messengr:CREATE_ADD_BOOK")
   aTmpItems[1] = new item("Adding a Name to Your Address Book", "mess.htm#ADD_USER_PROPERTIES", "nethelp:netscape/Messengr:ADD_USER_PROPERTIES")
   aTmpItems[2] = new item("Adding Notes to an Address Card", "mess.htm#ADD_USER_NOTES", "nethelp:netscape/Messengr:ADD_USER_NOTES")
   aTmpItems[3] = new item("Adding Contact Information to An Address Card", "mess.htm#ADD_USER_CONTACT", "nethelp:netscape/Messengr:ADD_USER_CONTACT")
   aTmpItems[4] = new item("Adding Netscape Conference Information", "mess.htm#ADD_USER_NETSCAPE_COOLTALK", "nethelp:netscape/Messengr:ADD_USER_NETSCAPE_COOLTALK")
   aTmpItems[5] = new item("Creating a Mailing List", "mess.htm#ADD_LIST_MAILING_LIST", "nethelp:netscape/Messengr:ADD_LIST_MAILING_LIST")
   aTmpItems[6] = new item("Searching an Address Book", "mess.htm#SEARCH_ADDRESS_BOOK", "nethelp:netscape/Messengr:SEARCH_ADDRESS_BOOK")
   aTmpItems[7] = new item("Looking Up Addresses through a Directory Service", "mess.htm#SEARCH_LDAP", "nethelp:netscape/Messengr:SEARCH_LDAP")
   aTmpItems[8] = new item("Selecting Addresses", "mess.htm#SELECT_ADDRESSES", "nethelp:netscape/Messengr:SELECT_ADDRESSES")
   aTmpItems[9] = new item("Importing Address Books and Mail Messages", "mess.htm#import_address_book", "nethelp:netscape/Messengr:import_address_book")
   aTmpItems[10] = new item("Exporting an Address Book", "mess.htm#export_address_book", "nethelp:netscape/Messengr:export_address_book")
   aTmpItems[11] = new item("Adding or Updating Directory Servers", "mess.htm#LDAP_SERVER_PROPERTIES", "nethelp:netscape/Messengr:LDAP_SERVER_PROPERTIES")
   aTmpItems[12] = new item("Selecting a Directory for Offline Use", "mess.htm#ADD_SERVER_OFFLINE", "nethelp:netscape/Messengr:ADD_SERVER_OFFLINE")
   aTmpContainers[4] = new container("Using an Address Book", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Creating a Folder", "mess.htm#FILING_MESSAGES", "nethelp:netscape/Messengr:FILING_MESSAGES")
   aTmpItems[1] = new item("Renaming a Folder", "mess.htm#rename_folder", "nethelp:netscape/Messengr:rename_folder")
   aTmpItems[2] = new item("Filing Messages", "mess.htm#OPENING_FOLDERS", "nethelp:netscape/Messengr:OPENING_FOLDERS")
   aTmpItems[3] = new item("Setting Folder Properties", "mess.htm#MAIL_FOLDER_PROPERTIES_GENERAL", "nethelp:netscape/Messengr:MAIL_FOLDER_PROPERTIES_GENERAL")
   aTmpItems[4] = new item("Using the Folder Properties Sharing Panel", "mess.htm#MAIL_FOLDER_PROPERTIES_SHARING", "nethelp:netscape/Messengr:MAIL_FOLDER_PROPERTIES_SHARING")
   aTmpItems[5] = new item("Using the Folder Properties Download Options Panel", "mess.htm#MAIL_FOLDER_PROPERTIES_DOWNLOAD", "nethelp:netscape/Messengr:MAIL_FOLDER_PROPERTIES_DOWNLOAD")
   aTmpItems[6] = new item("Creating Message Filters", "mess.htm#MAIL_FILTERS", "nethelp:netscape/Messengr:MAIL_FILTERS")
   aTmpItems[7] = new item("Specifying Settings for Message Filters", "mess.htm#FILTER_RULES", "nethelp:netscape/Messengr:FILTER_RULES")
   aTmpItems[8] = new item("Searching Through Messages", "mess.htm#SEARCH_MAILNEWS", "nethelp:netscape/Messengr:SEARCH_MAILNEWS")
   aTmpItems[9] = new item("Specifying Where to Search for Messages", "mess.htm#SEARCH_MAILNEWS_OPTIONS", "nethelp:netscape/Messengr:SEARCH_MAILNEWS_OPTIONS")
   aTmpItems[10] = new item("Adding and Removing Message Headers", "mess.htm#SEARCH_MAILNEWS_HEADERS", "nethelp:netscape/Messengr:SEARCH_MAILNEWS_HEADERS")
   aTmpContainers[5] = new container("Organizing Your Mail", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Setting General Mail and Newsgroup Preferences", "mess.htm#PREFERENCES_MAILNEWS_MAIN_PANE", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_MAIN_PANE")
   aTmpItems[1] = new item("Setting Your Identity Preferences", "mess.htm#PREFERENCES_MAILNEWS_IDENTITY", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_IDENTITY")
   aTmpItems[2] = new item("Setting Up Your Mail Servers", "mess.htm#PREFERENCES_MAILNEWS_MAILSERVER", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_MAILSERVER")
   aTmpItems[3] = new item("Setting General Mail Server Properties", "mess.htm#MAILSERVER_PROPERTY_GENERAL", "nethelp:netscape/Messengr:MAILSERVER_PROPERTY_GENERAL")
   aTmpItems[4] = new item("Setting POP3 Mail Server Properties", "mess.htm#MAILSERVER_PROPERTY_POP", "nethelp:netscape/Messengr:MAILSERVER_PROPERTY_POP")
   aTmpItems[5] = new item("Setting IMAP Mail Server Properties", "mess.htm#MAILSERVER_PROPERTY_IMAP", "nethelp:netscape/Messengr:MAILSERVER_PROPERTY_IMAP")
   aTmpItems[6] = new item("Setting Advanced IMAP Server Properties", "mess.htm#MAILSERVER_PROPERTY_ADVANCED", "nethelp:netscape/Messengr:MAILSERVER_PROPERTY_ADVANCED")
   aTmpItems[7] = new item("Identifying Your Newsgroup Servers", "mess.htm#PREFERENCES_MAILNEWS_GROUPSERVER", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_GROUPSERVER")
   aTmpItems[8] = new item("Setting Addressing Preferences", "mess.htm#PREFERENCES_MAILNEWS_ADDRESSING", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_ADDRESSING")
   aTmpItems[9] = new item("Setting Preferences for Outgoing Messages", "mess.htm#PREFERENCES_MAILNEWS_MESSAGES", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_MESSAGES")
   aTmpItems[10] = new item("Storing Messages and Sending Automatic Copies", "mess.htm#PREFERENCES_MAILNEWS_COPIES", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_COPIES")
   aTmpItems[11] = new item("Setting Message Formatting Preferences", "mess.htm#PREFERENCES_MAILNEWS_FORMATTING", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_FORMATTING")
   aTmpItems[12] = new item("Confirming That Your Message Was Received", "mess.htm#PREFERENCES_MAILNEWS_RECEIPTS", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_RECEIPTS")
   aTmpItems[13] = new item("Choosing Window Settings in Messenger", "mess.htm#PREFERENCES_MAILNEWS_WINDOW", "nethelp:netscape/Messengr:PREFERENCES_MAILNEWS_WINDOW")
   aTmpItems[14] = new item("Managing Your Disk Space", "mess.htm#PREFERENCES_ADVANCED_DISKSPACE", "nethelp:netscape/Messengr:PREFERENCES_ADVANCED_DISKSPACE")
   aTmpItems[15] = new item("Upgrading IMAP from Communicator 4.0 to 4.5", "mess.htm#IMAP_UPGRADE", "nethelp:netscape/Messengr:IMAP_UPGRADE")
   aTmpContainers[6] = new container("Setting Mail and Newsgroup Preferences", aTmpItems)

aDatasets["mess.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Viewing a Page", "nav.htm#nav_view", "nethelp:netscape/Navigatr:nav_view")
   aTmpItems[1] = new item("Moving to Another Page", "nav.htm#nav_openpage", "nethelp:netscape/Navigatr:nav_openpage")
   aTmpItems[2] = new item("Retracing Your Steps", "nav.htm#nav_retrace", "nethelp:netscape/Navigatr:nav_retrace")
   aTmpItems[3] = new item("Retracing Your Steps in Detail: The History List", "nav.htm#nav_histsearch", "nethelp:netscape/Navigatr:nav_histsearch")
   aTmpItems[4] = new item("Viewing a Page's Information", "nav.htm#nav_checksec", "nethelp:netscape/Navigatr:nav_checksec")
   aTmpItems[5] = new item("Viewing a Page's Source Code", "nav.htm#nav_checktec", "nethelp:netscape/Navigatr:nav_checktec")
   aTmpItems[6] = new item("Searching Within a Page", "nav.htm#nav_search", "nethelp:netscape/Navigatr:nav_search")
   aTmpContainers[0] = new container("Finding Information on the Web", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Creating a Bookmark", "nav.htm#nav_bcreate", "nethelp:netscape/Navigatr:nav_bcreate")
   aTmpItems[1] = new item("Creating an Internet Shortcut", "nav.htm#nav_bshort", "nethelp:netscape/Navigatr:nav_bshort")
   aTmpItems[2] = new item("Organizing Your Bookmarks", "nav.htm#nav_borg", "nethelp:netscape/Navigatr:nav_borg")
   aTmpItems[3] = new item("Searching the Bookmark List", "nav.htm#nav_bsearch", "nethelp:netscape/Navigatr:nav_bsearch")
   aTmpItems[4] = new item("Keeping Multiple Bookmark Lists", "nav.htm#nav_bmulti", "nethelp:netscape/Navigatr:nav_bmulti")
   aTmpItems[5] = new item("Checking the Freshness of Your Bookmarks", "nav.htm#nav_bfresh", "nethelp:netscape/Navigatr:nav_bfresh")
   aTmpContainers[1] = new container("Bookmarking Your Favorite Web Sites", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Copying Part of a Page", "nav.htm#nav_copy", "nethelp:netscape/Navigatr:nav_copy")
   aTmpItems[1] = new item("Saving a Page", "nav.htm#nav_save", "nethelp:netscape/Navigatr:nav_save")
   aTmpItems[2] = new item("Printing a Page", "nav.htm#nav_print", "nethelp:netscape/Navigatr:nav_print")
   aTmpContainers[2] = new container("Copying, Saving, and Printing pages", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Customizing the Toolbars", "nav.htm#nav_tool", "nethelp:netscape/Navigatr:nav_tool")
   aTmpItems[1] = new item("Adjusting the Component Bar", "nav.htm#nav_compbar", "nethelp:netscape/Navigatr:nav_compbar")
   aTmpItems[2] = new item("Changing Fonts", "nav.htm#nav_font", "nethelp:netscape/Navigatr:nav_font")
   aTmpItems[3] = new item("Changing Colors or Backgrounds", "nav.htm#nav_color", "nethelp:netscape/Navigatr:nav_color")
   aTmpItems[4] = new item("Specifying the Components That Appear at Startup", "nav.htm#nav_component", "nethelp:netscape/Navigatr:nav_component")
   aTmpItems[5] = new item("Specifying the Starting Page", "nav.htm#nav_home", "nethelp:netscape/Navigatr:nav_home")
   aTmpItems[6] = new item("Specifying How Long to Track History", "nav.htm#nav_track", "nethelp:netscape/Navigatr:nav_track")
   aTmpItems[7] = new item("Setting Language Priorities", "nav.htm#nav_lang", "nethelp:netscape/Navigatr:nav_lang")
   aTmpItems[8] = new item("Handling Different File Types", "nav.htm#nav_helper", "nethelp:netscape/Navigatr:nav_helper")
   aTmpItems[9] = new item("Finding the Pages You Want (Smart Browsing)", "nav.htm#nav_smartbrowse", "nethelp:netscape/Navigatr:nav_smartbrowse")
   aTmpContainers[3] = new container("Customizing Your Browser", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Automatic Loading", "nav.htm#nav_autoload", "nethelp:netscape/Navigatr:nav_autoload")
   aTmpItems[1] = new item("Handling Cookies", "nav.htm#nav_cook", "nethelp:netscape/Navigatr:nav_cook")
   aTmpItems[2] = new item("Changing Cache Settings", "nav.htm#nav_cache", "nethelp:netscape/Navigatr:nav_cache")
   aTmpItems[3] = new item("Getting the Latest Software Automatically", "nav.htm#nav_smartup", "nethelp:netscape/Navigatr:nav_smartup")
   aTmpItems[4] = new item("Setting Proxy Values", "nav.htm#nav_prox", "nethelp:netscape/Navigatr:nav_prox")
   aTmpContainers[4] = new container("Improving speed, efficiency, and privacy", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Setting Up Roaming Access", "nav.htm#nav_roam_intro", "nethelp:netscape/Navigatr:nav_roam_intro")
   aTmpItems[1] = new item("Specifying Where Your Roaming Profile Is Located", "nav.htm#nav_roam_profile", "nethelp:netscape/Navigatr:nav_roam_profile")
   aTmpItems[2] = new item("Specifying Files to Be Transferred at Startup and Shutdown", "nav.htm#nav_roam_files", "nethelp:netscape/Navigatr:nav_roam_files")
   aTmpContainers[5] = new container("Connecting from Anywhere", aTmpItems)

aDatasets["nav.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Reading Newsgroup Messages", "news.htm#opening_groups_server", "nethelp:netscape/News:opening_groups_server")
   aTmpItems[1] = new item("Subscribing to Newsgroups and IMAP Folders", "news.htm#SUBSCRIBE_LIST_ALL", "nethelp:netscape/News:SUBSCRIBE_LIST_ALL")
   aTmpItems[2] = new item("Searching for a Newsgroup", "news.htm#SUBSCRIBE_SEARCH", "nethelp:netscape/News:SUBSCRIBE_SEARCH")
   aTmpItems[3] = new item("Listing New Newsgroups", "news.htm#SUBSCRIBE_LIST_NEW", "nethelp:netscape/News:SUBSCRIBE_LIST_NEW")
   aTmpItems[4] = new item("Removing a Newsgroup", "news.htm#UNSUBSCRIBE", "nethelp:netscape/News:UNSUBSCRIBE")
   aTmpItems[5] = new item("Updating Newsgroups", "news.htm#DOWNLOADING_NEW", "nethelp:netscape/News:DOWNLOADING_NEW")
   aTmpContainers[0] = new container("Getting Started with Newsgroups", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Viewing and Changing Newsgroup Properties", "news.htm#NEWS_DISCUSSION_GENERAL", "nethelp:netscape/News:NEWS_DISCUSSION_GENERAL")
   aTmpItems[1] = new item("Setting Download Options for Newsgroups", "news.htm#NEWS_DISCUSSION_DOWNLOAD", "nethelp:netscape/News:NEWS_DISCUSSION_DOWNLOAD")
   aTmpItems[2] = new item("Setting Disk Space Properties for Newsgroups", "news.htm#NEWS_DISCUSSION_DISKSPACE", "nethelp:netscape/News:NEWS_DISCUSSION_DISKSPACE")
   aTmpContainers[1] = new container("Managing Your Newsgroups", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Posting Newsgroup Messages", "news.htm#about_posting", "nethelp:netscape/News:about_posting")
   aTmpItems[1] = new item("Contributing to Ongoing Discussions", "news.htm#REPLYING", "nethelp:netscape/News:REPLYING")
   aTmpContainers[2] = new container("Posting", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Adding a Newsgroup Server", "news.htm#ADD_SERVER", "nethelp:netscape/News:ADD_SERVER")
   aTmpItems[1] = new item("Changing Newsgroup Server Properties", "news.htm#DISCUSSION_HOST_PROPERTIES", "nethelp:netscape/News:DISCUSSION_HOST_PROPERTIES")
   aTmpContainers[3] = new container("Setting Up Newsgroups", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Going Offline to Work", "news.htm#off_work", "nethelp:netscape/News:off_work")
   aTmpItems[1] = new item("Preparing to Work Offline", "news.htm#OFFLINE_INTRO", "nethelp:netscape/News:OFFLINE_INTRO")
   aTmpItems[2] = new item("Downloading Items for Working Offline", "news.htm#DOWNLOAD_MESSAGES", "nethelp:netscape/News:DOWNLOAD_MESSAGES")
   aTmpItems[3] = new item("Updating the Items You Selected for Downloading", "news.htm#MAILNEWS_SYNCHRONIZE", "nethelp:netscape/News:MAILNEWS_SYNCHRONIZE")
   aTmpItems[4] = new item("Selecting Items for Download", "news.htm#MAILNEWS_SELECT_ITEMS", "nethelp:netscape/News:MAILNEWS_SELECT_ITEMS")
   aTmpContainers[4] = new container("Choosing Items to Read Offline", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("Setting Offline Preferences", "news.htm#PREFERENCES_OFFLINE", "nethelp:netscape/News:PREFERENCES_OFFLINE")
   aTmpItems[1] = new item("Downloading Newsgroups for Offline Reading", "news.htm#PREFERENCES_OFFLINE_GROUPS", "nethelp:netscape/News:PREFERENCES_OFFLINE_GROUPS")
   aTmpContainers[5] = new container("Setting Preferences", aTmpItems)

aDatasets["news.htm"] = aTmpContainers
aTmpContainers = new Array()
aTmpItems = new Array()
   aTmpItems[0] = new item("Server does not have a DNS entry", "trouble.htm#dns_entry", "nethelp:netscape/Trouble:dns_entry")
   aTmpItems[1] = new item("Connection reset by peer", "trouble.htm#peer_reset", "nethelp:netscape/Trouble:peer_reset")
   aTmpItems[2] = new item("Not implemented", "trouble.htm#not_implemented", "nethelp:netscape/Trouble:not_implemented")
   aTmpItems[3] = new item("Server error", "trouble.htm#server_error", "nethelp:netscape/Trouble:server_error")
   aTmpItems[4] = new item("Too much network traffic", "trouble.htm#network_traffic", "nethelp:netscape/Trouble:network_traffic")
   aTmpItems[5] = new item("404 Access denied", "trouble.htm#access_denied", "nethelp:netscape/Trouble:access_denied")
   aTmpItems[6] = new item("Disk Quota Exceeded (in Mail)", "trouble.htm#delete_failed", "nethelp:netscape/Trouble:delete_failed")
   aTmpItems[7] = new item("Can't read newsgroups", "trouble.htm#no_news", "nethelp:netscape/Trouble:no_news")
   aTmpItems[8] = new item("PowerPlant not installed (Mac OS)", "trouble.htm#power_plant", "nethelp:netscape/Trouble:power_plant")
   aTmpItems[9] = new item("Unknown error in Address book (Mac OS)", "trouble.htm#address_book", "nethelp:netscape/Trouble:address_book")
   aTmpContainers[0] = new container("Error Message Guide", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("How can I disable AOL Instant Messenger?", "trouble.htm#trouble_common_AIM", "nethelp:netscape/Trouble:trouble_common_AIM")
   aTmpItems[1] = new item("Why can't I alphabetize my bookmarks", "trouble.htm#trouble_common_alpha", "nethelp:netscape/Trouble:trouble_common_alpha")
   aTmpItems[2] = new item("How can I clear the Location  (Netsite) drop-down list of web sites (Windows only)?", "trouble.htm#trouble_common_clearloc", "nethelp:netscape/Trouble:trouble_common_clearloc")
   aTmpItems[3] = new item("I can't find the Navigator window", "trouble.htm#trouble_find_nav", "nethelp:netscape/Trouble:trouble_find_nav")
   aTmpItems[4] = new item("How do I clear the disk cache?", "trouble.htm#trouble_cache", "nethelp:netscape/Trouble:trouble_cache")
   aTmpItems[5] = new item("Can I navigate without using a mouse?", "trouble.htm#trouble_navigate", "nethelp:netscape/Trouble:trouble_navigate")
   aTmpItems[6] = new item("I'm stuck on a page: the Back button isn't working", "trouble.htm#trouble_stuck", "nethelp:netscape/Trouble:trouble_stuck")
   aTmpContainers[1] = new container("Common Problems", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("I forgot my password (somone else set my password)", "trouble.htm#forgot_pass", "nethelp:netscape/Trouble:forgot_pass")
   aTmpItems[1] = new item("Why can't I encrypt a message or add my digital signature?", "trouble.htm#cant_encrypt", "nethelp:netscape/Trouble:cant_encrypt")
   aTmpItems[2] = new item("Why can't I forward a decrypted Message?", "trouble.htm#HELP_SEC_WARNING_FORWARDING", "nethelp:netscape/Trouble:HELP_SEC_WARNING_FORWARDING")
   aTmpItems[3] = new item("Why can't I decrypt a message or page?", "trouble.htm#decrypt_message", "nethelp:netscape/Trouble:decrypt_message")
   aTmpItems[4] = new item("What does Possible Message Tampering mean?", "trouble.htm#tamper", "nethelp:netscape/Trouble:tamper")
   aTmpItems[5] = new item("What do I do when I see a Java download alert?", "trouble.htm#java_alert", "nethelp:netscape/Trouble:java_alert")
   aTmpContainers[2] = new container("Security and Warnings", aTmpItems)

aTmpItems = new Array()
   aTmpItems[0] = new item("How do I know when I have new mail?", "trouble.htm#trouble_mail_notify", "nethelp:netscape/Trouble:trouble_mail_notify")
   aTmpItems[1] = new item("How do I convert from a different mail system (like Eudora or Outlook Express) to Netscape Messenger?", "trouble.htm#trouble_switch", "nethelp:netscape/Trouble:trouble_switch")
   aTmpItems[2] = new item("How do I make Netscape start up with a mail window instead of the browser window?", "trouble.htm#trouble_start_window", "nethelp:netscape/Trouble:trouble_start_window")
   aTmpItems[3] = new item("How do I send email without showing the recipient's addresses or name in the header?", "trouble.htm#trouble_email_noshow", "nethelp:netscape/Trouble:trouble_email_noshow")
   aTmpItems[4] = new item("Why can't I read newsgroups?", "trouble.htm#trouble_no_news2", "nethelp:netscape/Trouble:trouble_no_news2")
   aTmpItems[5] = new item("Why is Messenger asking for my user name and password?", "trouble.htm#trouble_usr_passwd", "nethelp:netscape/Trouble:trouble_usr_passwd")
   aTmpItems[6] = new item("Why do I see the Mail & Newsgroups set-up screen when I open my Inbox or click Get Msg?", "trouble.htm#trouble_mail_wzrd", "nethelp:netscape/Trouble:trouble_mail_wzrd")
   aTmpItems[7] = new item("Why can't I get new messages over my Dial-up connection?", "trouble.htm#trouble_dialup_messg", "nethelp:netscape/Trouble:trouble_dialup_messg")
   aTmpItems[8] = new item("Newsgroup Troubles", "trouble.htm#trouble_news", "nethelp:netscape/Trouble:trouble_news")
   aTmpContainers[3] = new container("Messenger Problems", aTmpItems)

aDatasets["trouble.htm"] = aTmpContainers
aTmpContainers = new Array()
}
