#!/bin/sh

prefix=/usr/X11R6
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: Magick-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--cppflags] [--ldflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 4.2.2
      ;;
    --cflags)
      echo '-g -O2'
      ;;
    --cppflags)
      echo '-I/usr/X11R6/include/X11 -I/usr/X11R6/include'
      ;;
    --ldflags)
      echo '-L/usr/X11R6/lib -L/usr/X11R6/lib'
      ;;
    --libs)
      echo '-L/usr/X11R6/lib -lMagick  -ltiff -ljpeg -lpng -lXext -lXt -lX11 -lm'
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

