#!/bin/sh
insmod parport
insmod parport_pc
insmod lp

#/var/spool/lpd/postscript/deskjet.filter < $1 > /dev/lp0
#gs -q -dSAFER -sDEVICE=deskjet -r300x300 -sPAPERSIZE=letter -sOutputFile=- - -dFirstPage=$2 -dLastPage=$3 < $1 > /dev/lp0
gs -r150 -sOutputFile=/dev/lp0 $1
