#!/bin/sh
#for i in *[1,3,5,7,9].pbm; do pbmtolj $i > /dev/lp0; done

#Use the first for printing in reverse order, the second for regular order
for x in `seq 9 -2 1`	
#for x in `seq 1 2 9`
do
for i in *$x.pbm; do pbmtolj -res 300 $i > /dev/lp0 ; done
done
