#!/bin/sh
insmod parport
insmod parport_pc
insmod lp

#/var/spool/lpd/postscript/deskjet.filter < $1 > /dev/lp0
#gs -q -dSAFER -sDEVICE=deskjet -r300x300 -sPAPERSIZE=letter -sOutputFile=- - -dFirstPage=$2 -dLastPage=$3 < $1 > /dev/lp0
gs -r300 -sOutputFile=/dev/lp0 $1


##These are three options for printing.  You can delete lines in #.
##The second method is supposed to let you print a selection of pages.
##The first method requires a deskjet.filter and lpd and 'user'.
##The third method uses my default deskjet device.  You can specify
##some other device and use a gs default instead of the smaller HP one.
