#
# tclxConfig.sh - This file is generated by the TclX configure script to
# assist in linking with TclX (libtclx.a).  It is a shell scripted designed to
# be sourced by configure scripts.  The system libraries defined in here
# need to be used in addition to those defined in tclConfig.sh.  See
# tclExtend.h for a full expanation of the version numbers.
#
# System: Linux-2.2.3
# Date:   Wed Mar 24 19:09:23 CST 1999
#

#
# Version numbers for TclX (see tclExtend.h for details).
#
TCLX_FULL_VERSION='8.0.4'
TCLX_VERSION='8.0.4'

#
# Defines for cpp.
#
TCLX_DEFS=' -DNO_SYS_SELECT_H=1 -DSTDC_HEADERS=1 -DRETSIGTYPE=void '

#
# Additional libraries added by TclX.
#
TCLX_LIBS=''

#
# String to pass to linker to pick up the TclX library from its
# build directory.
#
TCLX_BUILD_LIB_SPEC='-L/SAVE/tcl/tclX8.0.4/tcl/unix -ltclx8.0.4'

#
# String to pass to linker to pick up the TclX library from its
# installed directory.
#
TCLX_LIB_SPEC='-L/usr/lib -ltclx8.0.4'

#
# Search flags that specify how to find the TclX shared libraries at run time
# on some systems.
#
TCLX_LD_SEARCH_FLAGS=''


