#
# tkxConfig.sh - This file is generated by the TclX configure script to
# assist in linking with TclX Tk support (libtkx.a).  It is a shell scripted
# designed to be sourced by configure scripts.  The system libraries defined
# in here need to be used in addition to those defined in tclConfig.sh,
# tclxConfig.sh and tkConfig.sh.  See tclExtend.h for a full expanation of the
# version numbers.  No values are currently filled in for TKX_LIBS.  Its just
# kept for future expansibility.
#
# System: Linux-2.2.3
# Date:   Wed Mar 24 19:09:23 CST 1999
#

#
# Version number for TkX (see tclExtend.h for details).
#
TKX_FULL_VERSION='8.0.4'

#
# Defines for cpp.
#
TKX_DEFS=' -DNO_SYS_SELECT_H=1 -DSTDC_HEADERS=1 -DRETSIGTYPE=void '

#
# Additional libraries added by TclX.
#
TKX_LIBS=''

#
# String to pass to linker to pick up the TkX library from its
# build directory.
#
TKX_BUILD_LIB_SPEC='-L/SAVE/tcl/tclX8.0.4/tk/unix -ltkx8.0.4'

#
# String to pass to linker to pick up the TclX library from its
# installed directory.
#
TKX_LIB_SPEC='-L/usr/lib -ltkx8.0.4'


